### ISSUE TITLE
README.md not clear about opening the program

### ISSUE THREAD

**Issue by miguelfs** [hugofloresgarcia/unloop#1]
Hi, Hugo. Congratulations on this project. AK's Twitter account retweeted your video and I've just watched it.

I've cloned the repository and installed the dependencies using pip, but it is unclear to me how to run the program.

**Comment by hugofloresgarcia** [comment]
Hi Miguel, thanks!

`unloop` runs as a Max Patch, so you'll need to open `unloop.maxpat` using Max to run it. I've updated the README to clarify this a bit. Let me know if there's anything else I can do to improve the instructions! :)
